### ISSUE TITLE
Check for extract.signature()

### ISSUE THREAD

**Issue by anfederico** [Vanessa104/OmicSig_Shiny#8]
The `extract.signature` method should have a check for signatures that don't have differential expression data.

e.g.
```R
 extract.signature = function(conditions) {
        if (is.null(self$difexp)) {
            stop("...")
        }
     
    ...
 }

```

**Comment by tetomonti** [comment]
The idea is to allow to upload signatures even when no diffanal table is available (e.g., a signature reported in a paper). Perhaps a warning?

**Comment by anfederico** [comment]
This would just stop the user from trying to filter a new signature from the differential expression table. They could directly access it by just calling `self$signature`. Although maybe `extract.signature` could handle both of these uses based on what's available or the conditions passed?

**Comment by tetomonti** [comment]
Ah yes, makes sense.

**Comment by Vanessa104** [comment]
What about gives a warning and then return empty results? So if the user is manipulating multiple OmicSig obj together, the whole pipeline won't stop and broke?

**Comment by anfederico** [comment]
I think it should explicitly stop because it will likely get an error from dplyr. For manipulating multiple objects in a pipeliner, there should be error handling happening at that higher level for signature objects without difexp data.

**Comment by Vanessa104** [comment]
you mean, when manipulating multiple objects together, before actually go into each object ( OmicObj1$extract.signatures(...), OmicObj2$extract.signatures(...) ) we check if they all have difexp?

**Comment by Vanessa104** [comment]
But yeah stop makes sense! I will make that. Thx for bringing this up!!
